config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('scraping.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

scraping/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import DashBoardView, FBPageView, FBPageCreateView, AdView,AdUpdateView, AdSoretedByDateView, AdSoretedByFBPageView, AdFavoriteListView, AdMemoView, LPListView, FBPageDetailView, FBPageUpdateView

app_name = 'scraping'

urlpatterns = [
    path('', DashBoardView.as_view(), name='dashboard'),
    path('fbpage/', FBPageView.as_view(), name='fbpage'),
    path('fbpage/create/', FBPageCreateView.as_view(), name='fbpage_create'),
    path('fbpage/update/<int:pk>', FBPageUpdateView.as_view(), name='fbpage_update'),
    path('fbpage/detail/<int:pk>', FBPageDetailView.as_view(), name='fbpage_detail'),
    path('ad/', AdView.as_view(), name='ad'),
    path('ad/<int:pk>/update/', AdUpdateView.as_view(), name='ad_update'),
    path('ad/sorted_by_date/', AdSoretedByDateView.as_view(), name='ad_sorted_by_date'),
    path('ad/sorted_by_fbpage/', AdSoretedByFBPageView.as_view(), name='ad_sorted_by_fbpage'),
    path('ad/favorite_list/', AdFavoriteListView.as_view(), name='ad_favorite_list'),
    path('ad/memo/', AdMemoView.as_view(), name='ad_memo'),
    path('lp/list/', LPListView.as_view(), name='lp_list'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

scraping/models.py
from django.db import models
from django.db.models.deletion import CASCADE

# Create your models here.

class Page(models.Model):
    name = models.CharField(max_length=100, default='pagename')
    page_id = models.IntegerField(null=True, blank=True)
    likes = models.IntegerField(null=True, blank=True, default=0)
    category = models.CharField(max_length=200, null=True)
    scraped_at = models.DateTimeField(auto_now_add=True)
    is_notable = models.BooleanField(default=False)

    def __str__(self):
        return self.name



class Advertisement(models.Model):
    parent = models.ForeignKey(Page, on_delete=models.CASCADE)
    status = models.CharField(max_length=100, null = True)
    started_running_on = models.CharField(max_length=100, null = True)
    main_text = models.CharField(max_length=200, null=True)
    sub_text = models.CharField(max_length=200, null=True)# ?
    ad_id = models.IntegerField(null=True, blank=True, default=0)
    image_url = models.CharField(max_length=500, null=True)
    lp_url = models.CharField(max_length=500, null=True)
    memo = models.TextField(max_length=500, null=True, blank=True)
    scraped_at = models.DateTimeField(auto_now_add=True)
    is_favorite  = models.BooleanField(default=False)

    # def __str__(self):
    #     return self.main_text[:30]

scraping/views.py
from typing import Counter
from django.db import models
from django.shortcuts import redirect, render
from django.views.generic import TemplateView, ListView, CreateView, UpdateView, DetailView, DeleteView
from .models import Advertisement, Page
from django.urls import reverse_lazy
from django.views.generic.list import MultipleObjectMixin
from collections import Counter
# Create your views here.

class DashBoardView(TemplateView):
    template_name = "dashboard.html"

class FBPageView(ListView):
    template_name = "fbpage.html"
    paginate_by = 10
    page_num = Page.objects.only('page_id').annotate(latest=models.Min('scraped_at')).count()
    queryset = Page.objects.all()[::-1][:page_num]

class FBPageCreateView(CreateView):
    template_name = "fbpage_create.html"
    model = Page
    fields = ('page_id',)
    success_url = reverse_lazy('scraping:dashboard')

class FBPageUpdateView(UpdateView):
    template_name = "fbpage_update.html"
    model = Page
    fields = ('is_notable',)
    success_url = reverse_lazy('scraping:dashboard')

class FBPageDetailView(DetailView, MultipleObjectMixin):
    template_name = "fbpage_detail.html"
    model = Page
    paginate_by = 9

    def get_context_data(self, **kwargs):
        object_list = Advertisement.objects.filter(parent=self.object)
        context = super(FBPageDetailView, self).get_context_data(object_list=object_list, **kwargs)
        return context

class FBPageDeleteView(DeleteView):
    template_name = "fbpage_delete.html"
    model = Page

class AdView(ListView):
    template_name = "ad.html"
    model = Advertisement
    context_object_name = 'advertisements'
    paginate_by = 9

class AdUpdateView(UpdateView):
    template_name = "ad_update.html"
    model = Advertisement
    fields = ('memo', 'is_favorite')
    success_url = reverse_lazy('scraping:dashboard')


class AdSoretedByDateView(ListView):
    template_name = "ad_sorted_by_date.html"
    model = Page
    context_object_name = 'pages'
    queryset = Page.objects.order_by('-scraped_at')
    paginate_by = 12

class AdSoretedByFBPageView(ListView):
    template_name = "ad_sorted_by_fbpage.html"
    model = Page
    context_object_name = 'pages'
    queryset = Page.objects.order_by('page_id')
    paginate_by = 12

class LPListView(TemplateView):
    template_name = "lp_list.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        lp_urls = []
        for ad in Advertisement.objects.all():
            lp_urls.append(ad.lp_url)
        count = Counter(lp_urls)
        count_lp_url = []
        for key, val in count.items():
            count_lp_url.append([key,val])
        context['count_lp_url'] = count_lp_url
        return context

class AdMemoView(ListView):
    template_name = "ad_memo.html"
    model = Advertisement
    context_object_name = 'advertisements'
    paginate_by = 12

class AdFavoriteListView(ListView):
    template_name = "ad_favorite_list.html"
    model = Advertisement
    context_object_name = 'advertisements'
    paginate_by = 12

templates/ad.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
      <div class="row">
          <div class="col-md-5">
              <form class="form-inline" method="get">
                  <div class="checkbox">
                      <label>
                          <input type="checkbox" name="is_favorite"> お気に入りのみ
                      </label>
                  </div>
                  <button class="btn btn-primary" type="submit">検索</button>
              </form>
          </div>
      </div>
  </div>

  <div class="container">
      <div class="row">
        {% for ad in advertisements %}
          <div class="col-12 col-sm-6 col-md-4">
            <div class="card">
              <div class="card-header">
                
                <span><i class="fas fa-toggle-off"></i> {{ad.status}}</span>
                
                <br>
                <span>掲載開始日:2019/12/01</span>
                <br>
                <span>ID:<a href="/ad/sorted_fbad_id?fbad_id=1111111114">{{ad.ad_id}}</a></span>
              </div>
              <div class="card-body">
                <p class="card-title mb-3"><a href="https://www.facebook.com/ads/library/?active_status=all&amp;ad_type=all&amp;country=ALL&amp;impression_search_field=has_impressions_lifetime&amp;view_all_page_id=105178707637464" rel="noopener noreferrer" target="_blank">{{ad.parent.category}}</a>
                </p>
                <p class="card-text">{{ad.main_text}}</p>
              </div>
              
              <div class="card-body">
                <a href="{{ad.image_url}}">画像・動画</a>
              </div>
              
          
              <div class="card-body">
                <p class="card-subtitle mb-3 text-muted">{{ad.sub_text}}</p>
                <p class="card-subtitle mb-2 text-muted"></p>
                <p class="card-text mb-2 text-muted">so-tool.com</p>
                
                <a href="{{ad.lp_url}}" target="_blank" rel="noopener noreferrer"><button type="button" class="btn btn-secondary btn-sm">Shop Now</button></a>
                
          
              </div>
              <div class="card-footer">
                <p>
                  <span>取得日:{{ad.parent.scraped_at}}</span><br>
                  
                  <span>LP:
                    <a class="card-link" href="https://www.google.com/" target="_blank" rel="noopener noreferrer">URL</a>
                  </span>
                </p>
                <p>{{ad.memo}}</p>
                <p>
                  <a href="{% url 'scraping:ad_update' ad.pk %}"><button class="btn btn-primary" type="submit">編集</button></a>
                </p>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
      <div>
        {% if is_paginated %}
        <ul class="pagination">
          {% if page_obj.has_previous %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
          {% else %}
          <li class="disabled"><span class="page-link">&laquo;</span></li>
          {% endif %}
          
          {% for i in paginator.page_range %}
          {% if page_obj.number == i %}
          <li class="page-item active"><span class="page-link">{{ i }}</span></li>
          {% else %}
          <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
          {% endif %}
          {% endfor %}
          
          {% if page_obj.has_next %}
          <li><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
          {% else %}
          <li class="disabled"><span class="page-link">&raquo;</span></li>
          {% endif %}
        </ul>
        {% endif %}
      </div>
  </div>
{% endblock content %}

templates/ad_favorite_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-5">
            <form class="form-inline" method="get">
                <div class="checkbox">
                    <label>
                        <input type="checkbox" name="is_favorite"> お気に入りのみ
                    </label>
                </div>
                <button class="btn btn-primary" type="submit">検索</button>
            </form>
        </div>
    </div>
</div>

<div class="container">
  <div class="row">
    {% for ad in advertisements %}
      {% if ad.is_favorite %}
        <div class="col-12 col-sm-6 col-md-4">
          <div>{{ad.is_favorite}}</div>
          <div class="card">
            <div class="card-header">
              
              <span><i class="fas fa-toggle-off"></i> {{ad.status}}</span>
              
              <br>
              <span>掲載開始日:2019/12/01</span>
              <br>
              <span>ID:<a href="/ad/sorted_fbad_id?fbad_id=1111111114">{{ad.ad_id}}</a></span>
            </div>
            <div class="card-body">
              <p class="card-title mb-3"><a href="https://www.facebook.com/ads/library/?active_status=all&amp;ad_type=all&amp;country=ALL&amp;impression_search_field=has_impressions_lifetime&amp;view_all_page_id=105178707637464" rel="noopener noreferrer" target="_blank">{{ad.parent.category}}</a>
              </p>
                <p class="card-text">{{ad.main_text}}</p>
              </div>
              
              <div class="card-body">
                <a href="{{ad.image_url}}">画像・動画</a>
              </div>
              
              
              <div class="card-body">
                <p class="card-subtitle mb-3 text-muted">{{ad.sub_text}}</p>
                <p class="card-subtitle mb-2 text-muted"></p>
                <p class="card-text mb-2 text-muted">so-tool.com</p>
                
                <a href="https://www.google.com/" target="_blank" rel="noopener noreferrer"><button type="button" class="btn btn-secondary btn-sm">Shop Now</button></a>
                
                
              </div>
              <div class="card-footer">
                <p>
                  <span>取得日:{{ad.parent.scraped_at}}</span><br>
                  
                  <span>LP:
                    <a class="card-link" href="https://www.google.com/" target="_blank" rel="noopener noreferrer">URL</a>
                  </span>
                </p>
                <p>{{ad.memo}}</p>
                <p>
                  <a href="{% url 'scraping:ad_update' ad.pk %}"><button class="btn btn-primary" type="submit">編集</button></a>
                </p>
              </div>
            </div>
          </div>
      {% endif %}
    {% endfor %}
  </div>
</div>
{% endblock content %}

templates/ad_memo.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <div class="row">
      {% for ad in advertisements %}
        {% if ad.memo is not None %}
          <div class="col-12 col-sm-6 col-md-4">
            <div class="card">
              <div class="card-header">
                
                <span><i class="fas fa-toggle-off"></i> {{ad.status}}</span>
                
                <br>
                <span>掲載開始日:2019/12/01</span>
                <br>
                <span>ID:<a href="/ad/sorted_fbad_id?fbad_id=1111111114">{{ad.ad_id}}</a></span>
              </div>
              <div class="card-body">
                <p class="card-title mb-3"><a href="https://www.facebook.com/ads/library/?active_status=all&amp;ad_type=all&amp;country=ALL&amp;impression_search_field=has_impressions_lifetime&amp;view_all_page_id=105178707637464" rel="noopener noreferrer" target="_blank">{{ad.parent.category}}</a>
                </p>
                <p class="card-text">{{ad.main_text}}</p>
              </div>
              
              <div class="card-body">
                <a href="{{ad.image_url}}">画像・動画</a>
              </div>
              
          
              <div class="card-body">
                <p class="card-subtitle mb-3 text-muted">{{ad.sub_text}}</p>
                <p class="card-subtitle mb-2 text-muted"></p>
                <p class="card-text mb-2 text-muted">so-tool.com</p>
                
                <a href="https://www.google.com/" target="_blank" rel="noopener noreferrer"><button type="button" class="btn btn-secondary btn-sm">Shop Now</button></a>
              </div>
              <div class="card-footer">
                <p>
                  <span>取得日:{{ad.parent.scraped_at}}</span><br>
                  
                  <span>LP:
                    <a class="card-link" href="https://www.google.com/" target="_blank" rel="noopener noreferrer">URL</a>
                  </span>
                </p>
                <p>{{ad.memo}}</p>
                <p>
                  <a href="{% url 'scraping:ad_update' ad.pk %}"><button class="btn btn-primary" type="submit">編集</button></a>
                </p>
              </div>
            </div>
          </div>
        {% endif %}
      {% endfor %}
    </div>
  </div>
{% endblock content %}

templates/ad_sorted_by_date.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <table class="table">
        <thead>
            <tr>
                <!-- <th scope="col">FB広告ID</th> -->
                <th scope="col">最新取得日</th>
                <th scope="col">FBページ名</th>

            </tr>
        </thead>
        <tbody>
            {% for page in pages %}
                {% if page.name %}
                <tr>
                    <td>{{page.scraped_at}}</td>
                    <td><a href="/page/sorted_detail?check_date=2019-12-18&amp;fbpage_id=105178707637464">{{ page.name }}</a>
                    </td>
                </tr>
                {% endif %}
            {% endfor %}
        </tbody>
    </table>
    <div>
        {% if is_paginated %}
        <ul class="pagination">
            {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
            {% else %}
            <li class="disabled"><span class="page-link">&laquo;</span></li>
            {% endif %}
            
            {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
            <li class="page-item active"><span class="page-link">{{ i }}</span></li>
            {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
            {% endfor %}
            
            {% if page_obj.has_next %}
            <li><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
            {% else %}
            <li class="disabled"><span class="page-link">&raquo;</span></li>
            {% endif %}
        </ul>
        {% endif %}
    </div>
</div>
    {% endblock content %}

templates/ad_sorted_by_fbpage.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">FBページ名</th>
                <th scope="col">最新取得日</th>
            </tr>
        </thead>
        <tbody>
            {% for page in pages %}
                {% if page.name %}
                <tr>
                    <td>{{page.name}}</td>
                    <td><a href="/ad/sorted_detail?check_date=2019-12-19&amp;fbpage_id=105178707637464">{{page.scraped_at|date:'Y年m月d日'}}</a>
                    </td>
                </tr>
                {% endif %}
            {% endfor %}
        </tbody>
    </table>
    <div>
        {% if is_paginated %}
        <ul class="pagination">
            {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
            {% else %}
            <li class="disabled"><span class="page-link">&laquo;</span></li>
            {% endif %}
            
            {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
            <li class="page-item active"><span class="page-link">{{ i }}</span></li>
            {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
            {% endfor %}
            
            {% if page_obj.has_next %}
            <li><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
            {% else %}
            <li class="disabled"><span class="page-link">&raquo;</span></li>
            {% endif %}
        </ul>
        {% endif %}
    </div>
</div>
{% endblock content %}

templates/dashboard.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <p>ようこそdemoさん</p>
        <div class="lead"><a href="{% url 'scraping:fbpage' %}">Fbpage一覧</a></div>
        <p>登録したFbpageの一覧で、登録の新しい順に並んでいます。リンク先は公式の広告ライブラリに遷移します。</p>
        <div class="lead"><a href="{% url 'scraping:fbpage_create' %}">Fbpage IDの登録</a></div>
        <p>スクレイピング対象のFbpageのID登録画面です。</p>
        <div class="lead"><a href="{% url 'scraping:ad' %}">広告一覧</a></div>
        <p>広告の全一覧です。</p>
        <div class="lead"><a href="{% url 'scraping:ad_sorted_by_date' %}">日付で広告をソート</a></div>
        <p>日付でソートした上で、Fbpageで選べるようにしています。</p>
        <div class="lead"><a href="{% url 'scraping:ad_sorted_by_fbpage' %}">Fbpageで広告をソート</a></div>
        <p>Fbpageでソートした上で、日付で選べるようにしています。</p>
        <div class="lead"><a href="{% url 'scraping:lp_list' %}">記事LPの登録数順</a></div>
        <p>記事LPのURL登録数が多い順に並べています。露出量の多い記事LPがチェックできます。</p>
        <div class="lead"><a href="{% url 'scraping:ad_favorite_list' %}">お気に入り</a></div>
        <p>お気に入りに入れた一覧です。</p>
        <div class="lead"><a href="{% url 'scraping:ad_memo' %}">メモ</a></div>
        <p>メモを記入した一覧です。</p>
        <p>
            <a href="{% url 'logout' %}">
                <button type="button" class="btn btn-primary btn-sm">ログアウト</button>
            </a>
        </p>
    </div>
{% endblock content %}

templates/fbpage.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-6">
            <form class="form-inline">{% csrf_token %}
                <div class="form-group">
                    <input class="form-control" type="text" name="freetext" placeholder="Facebookページ名" value="">
                </div>
                <div class="checkbox">
                    <label>
                    <input type="checkbox" name="is_notice"> 注目のみ
                    </label>
                </div>
                <button type="submit" class="btn btn-primary">検索</button>
            </form>
        </div>
        <div class="col-md-3 offset-md-3 text-right">
            <a class="btn btn-primary" href="/fbpage/create">Facebookページ追加</a>
        </div>
    </div>
</div>

<div class="container-fluid mt-2">
    <div class="row">
        <div class="col-md-12">
            <table class="table">
                <thead>
                    <tr>
                    <th scope="col">Facebookページ名</th>
                    <th scope="col">いいね数</th>
                    <th scope="col">カテゴリ名</th>
                    <th scope="col">注目状況</th>
                    </tr>
                </thead>
                <div>{{object_list}}</div>
                <tbody>
                    {% for page in object_list %}
                        {% if page.name %}
                        <tr>
                            <td>
                                <a href="{% url 'scraping:fbpage_detail' page.pk %}">{{page.name}}</a>
                            </td>
                            <td>{{page.likes}}</td>
                            <td>{{page.scraped_at}}</td>
                            <td>
                                {% if page.is_notable %}
                                <i class="fas fa-flag"></i>
                                {% endif %}
                            </td>
                        </tr>
                        {% endif %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<div>
    {% if is_paginated %}
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
        {% else %}
        <li class="disabled"><span class="page-link">&laquo;</span></li>
        {% endif %}
        
        {% for i in paginator.page_range %}
        {% if page_obj.number == i %}
        <li class="page-item active"><span class="page-link">{{ i }}</span></li>
        {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
        {% endfor %}
        
        {% if page_obj.has_next %}
        <li><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
        {% else %}
        <li class="disabled"><span class="page-link">&raquo;</span></li>
        {% endif %}
    </ul>
    {% endif %}
</div>

{% endblock content %}

templates/fbpage_create.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <form method="POST">{% csrf_token %}
        <table class="table">
            <tbody>
                <tr>
                    <th>
                        <label for="id_fbpage_id">Fbpage id:</label>
                    </th>
                    <td>
                        {{form}}
                    </td>
                </tr>
            </tbody>
        </table>
        <button class="btn btn-primary" type="submit">追加</button>
    </form>
</div>
{% endblock content %}

templates/fbpage_delete.html
{% extends "base.html" %}

{% block content %}
<section>
<div class="container">
    <div class="row">
    <div class="col-md-9">
        <h2>ユーザー設定</h2>
    </div>
    <div class="col-md-3" style="text-align: right">
        <a class="btn btn-primary" href="{% url 'scraping:fbpage_update' page.pk %}">編集</a>
    </div>
    </div>
    <div class="row">
    <div class="col-md-12">
        <ul class="listgroup" style="padding-left: 0;">
        <li class="list-group-item">
            <i class="fas fa-flag"></i>注目状況：
            
            注目しない
            
        </li>
        </ul>
    </div>
    </div>
</div>
</section>
{% endblock content %}

templates/fbpage_detail.html
{% extends "base.html" %}

{% block content %}
<section>
<div class="container">
    <div class="row">
    <div class="col-md-8">
        <div>テスト</div>
    </div>
    <div class="col-md-4" style="text-align: right">
        <a class="btn btn-info btn-sm" href="https://www.facebook.com/ads/library/?active_status=all&amp;ad_type=all&amp;country=JP&amp;impression_search_field=has_impressions_lifetime&amp;view_all_page_id={{page.page_id}}" target="_blank" rel="noopener noreferrer">
        広告ライブラリへ</a>
    </div>
    </div>
    <div class="row">
    <div class="col-md-12">
        <ul class="listgroup" style="padding-left: 0;">
        <li class="list-group-item">FBページID：{{page.page_id}}</li>
        <li class="list-group-item">カテゴリ：{{page.category}}</li>
        <li class="list-group-item">いいね数：{{page.likes}}</li>
        </ul>
    </div>
    </div>
</div>
</section>
<section>
<div class="container">
    <div class="row">
    <div class="col-md-9">
        <h2>ユーザー設定</h2>
    </div>
    <div class="col-md-3" style="text-align: right">
        <a class="btn btn-primary" href="{% url 'scraping:fbpage_update' page.pk %}">編集</a>
    </div>
    </div>
    <div class="row">
    <div class="col-md-12">
        <ul class="listgroup" style="padding-left: 0;">
        <li class="list-group-item">
            <i class="fas fa-flag"></i>
            <span>注目状況：</span>
            {% if page.is_notable %}
                <span>注目する</span>
            {% else %}
                <span>注目しない</span>
            {% endif %}
            
        </li>
        </ul>
    </div>
    </div>
</div>
</section>

<section>
<div class="container">
    <h2>関連する広告</h2>
    <div class="row">
        {% for ad in object_list %}
        <div class="col-12 col-sm-6 col-md-4">
        <div class="card">
            <div class="card-header">
            
            <span><i class="fas fa-toggle-off"></i> {{ad.status}}</span>
            
            <br>
            <span>掲載開始日:2019/12/01</span>
            <br>
            <span>ID:<a href="/ad/sorted_fbad_id?fbad_id=1111111114">{{ad.ad_id}}</a></span>
            </div>
            <div class="card-body">
            <p class="card-title mb-3"><a href="https://www.facebook.com/ads/library/?active_status=all&amp;ad_type=all&amp;country=JP&amp;impression_search_field=has_impressions_lifetime&amp;view_all_page_id=105178707637464" rel="noopener noreferrer" target="_blank">{{ad.parent.category}}</a>
            </p>
            <p class="card-text">{{ad.main_text}}</p>
            </div>
            
            <div class="card-body">
            <a href="{{ad.image_url}}">画像・動画</a>
            </div>
            
        
            <div class="card-body">
            <p class="card-subtitle mb-3 text-muted">{{ad.sub_text}}</p>
            <p class="card-subtitle mb-2 text-muted"></p>
            <p class="card-text mb-2 text-muted">so-tool.com</p>
            
            <a href="{{ad.lp_url}}" target="_blank" rel="noopener noreferrer"><button type="button" class="btn btn-secondary btn-sm">Shop Now</button></a>
            
        
            </div>
            <div class="card-footer">
            <p>
                <span>取得日:{{ad.parent.scraped_at}}</span><br>
                
                <span>LP:
                <a class="card-link" href="https://www.google.com/" target="_blank" rel="noopener noreferrer">URL</a>
                </span>
            </p>
            <p>{{ad.memo}}</p>
            <p>
                <a href="{% url 'scraping:ad_update' ad.pk %}"><button class="btn btn-primary" type="submit">編集</button></a>
            </p>
            </div>
        </div>
        </div>
        {% endfor %}
    </div>
    <div>
        {% if is_paginated %}
        <ul class="pagination">
            {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
            {% else %}
            <li class="disabled"><span class="page-link">&laquo;</span></li>
            {% endif %}
            
            {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
            <li class="page-item active"><span class="page-link">{{ i }}</span></li>
            {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
            {% endfor %}
            
            {% if page_obj.has_next %}
            <li><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
            {% else %}
            <li class="disabled"><span class="page-link">&raquo;</span></li>
            {% endif %}
        </ul>
        {% endif %}
    </div>
</div>
</section>


{% endblock content %}